services:
  automated_django:
    #dns:
    #  - 10.202.10.202
    #  - 10.202.10.102
    build: .
#      context: .
#      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    #env_file: ./.env
