name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (for linting/tests if needed)
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'


    - name: Deploy to Localhost
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Debug: Check the file permissions and contents
        ls -l ~/.ssh
        cat ~/.ssh/deploy_key

        # Connect via SSH and deploy the Dockerized app
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key me@localhost << 'EOF'
          # Navigate to the project directory
          cd ~/Desktop/automated

          # Pull the latest changes
          git pull origin main

          # Build and deploy the updated Docker containers
          docker-compose down
          docker-compose up --build -d

          # Optional: Clean up unused Docker resources
          # docker system prune -f
        EOF

    - name: Clean up
      run: rm -f ~/.ssh/deploy_key

